polaris_ip: "192.155.1.80"
publish_period_ms: 20

trackers:
  - id: 0
    srom: "/home/ouspine/ros2_ws/ndisys_ros2/polaris_description/srom/BrainLabReference1.rom"
    topic_name: "brainlab_reference1"

  # - id: 1
  #   srom: "~/Desktop/ros2_/ur5_control/src/polaris_vega_interface/sroms/8700339.rom"
  #   topic_name: "world_tracker"

  # - id: 2
  #   srom: "~/Desktop/ros2_/ur5_control/src/polaris_vega_interface/sroms/8700340.rom"
  #   topic_name: "needle_tracker"
